version: '3.5'
services:
  myapp:
    network_mode: host
    image: myapp_img
    build:
      context: .
      dockerfile: Dockerfile   
    volumes:
      - ./build/libs:/app/build/libs
      - ./crypto:/app/crypto
      - ./ec-cakey.jks:/app/ec-cakey.jks
      - ./ec-cacert.pem:/app/ec-cacert.pem
      - ./resources:/app/resources
      - ./temperatura:/app/temperatura
    env_file:
      - .env

