version: '3.5'
services:
  myapp:
    image: cysec-docker.eng.it/eratosthenes/mudmanager:deploy-1.0.0-beta
    networks: 
      - net
    volumes:
      - ./build/libs:/app/build/libs
      - ./crypto:/app/crypto
      - ./ec-cakey.jks:/app/ec-cakey.jks
      - ./ec-cacert.pem:/app/ec-cacert.pem
      - ./resources:/app/resources
      - ./temperatura:/app/temperatura
    env_file:
      - .env
    environment:
      - PDP_PORT=${PDP_PORT}
      - PDP_CONFIG=${PDP_CONFIG}
      - PDP_KS=${PDP_KS}
      - PDP_PW=${PDP_PW}
      - PDP_ALIAS=${PDP_ALIAS}
      - DLT_IP=${DLT_IP}
      - DLT_PORT=${DLT_PORT}
      - IDAGENT_KS=${IDAGENT_KS}
      - IDAGENT_PW=${IDAGENT_PW}
      - IDAGENT_ALIAS=${IDAGENT_ALIAS}
      - IDAGENT_CERT=${IDAGENT_CERT}
      - IDAGENT_PORT=${IDAGENT_PORT}
      - IDAGENT_IP=${IDAGENT_IP}
      - RESOURCES=${RESOURCES}
    ports:
      - ${PDP_PORT}:${PDP_PORT}

networks:
    net:
        external: true
        name: eratosthenes-network
